version: "3"

services:
    nginx:
        image: linuxserver/nginx
        container_name: nginx
        environment:
            PUID: 0
            PGID: 0
            TZ: America/New_York
        volumes:
          - C:\Data\Docker\Nginx:/config
        ports:
          - 80:80
          - 443:443
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.2

    portainer:
        image: portainer/portainer
        container_name: portainer
        ports:
            - 9000:9000
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - C:\Data\Docker\Portainer:/data
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.3

    watchtower:
        image: v2tec/watchtower
        container_name: watchtower
        environment: 
            WATCHTOWER_NOTIFICATIONS: email
            WATCHTOWER_NOTIFICATION_EMAIL_FROM: btwestmo@gmail.com
            WATCHTOWER_NOTIFICATION_EMAIL_TO: btwestmo@gmail.com
            WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
            WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: btwestmo@gmail.com
            WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: add_app_password
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - C:\Data\Docker\Watchtower\config.json:/config.json
        command: --schedule "0 0 4 * * *" --cleanup
        networks:
            static-network:
               ipv4_address: 172.20.0.4

    plex:
        image: linuxserver/plex
        container_name: plex
        environment:
            PUID: 0
            PGID: 0
            VERSION: docker
        volumes:
            - C:\Data\Docker\Plex\Config:/config
            - C:\Data\Media\TV:/data/tvshows
            - C:\Data\Media\Movie:/data/movies
            - C:\Data\Docker\Plex\Transcode:/transcode
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.5

    tautulli:
        image: linuxserver/tautulli
        container_name: tautulli
        depends_on:
            - plex
        environment:
            PUID: 0
            PGID: 0
            TZ: America/New_York
        volumes:
            - C:\Data\Docker\Tautulli\Config:/config
            - C:\Data\Docker\Tautulli\Logs:/logs:ro
            - C:\Data\Docker\Shared:/shared
        ports:
            - 8181:8181
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.6

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        depends_on:
            - nzbget
        environment:
            PUID: 0
            PGID: 0
            TZ: America/New_York
            UMASK_SET: 022
        volumes:
            - C:\Data\Docker\Sonarr\Config:/config
            - C:\Data\Media\TV:/tv
            - C:\Data\Media\Downloads\:/downloads
        ports:
            - 8989:8989
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.7

    lidarr:
        image: linuxserver/lidarr
        container_name: lidarr
        environment:
            PUID: 0
            PGID: 0
            TZ: America/New_York
            UMASK_SET: 022
        volumes:
            - C:\Data\Docker\Lidarr\Config:/config
            - C:\Data\Media\Downloads:/downloads
            - C:\Data\Media\Music:/music
        ports:
            - 8686:8686
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.8

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
            PUID: 0
            PGID: 0
            TZ: America/New_York
        volumes:
            - C:\Data\Docker\Radarr:/config
            - C:\Data\Media\Downloads:/downloads
            - C:\Data\Media\Movie:/movies
        ports:
            - 7878:7878
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.9

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        environment:
            PUID: 0
            PGID: 0
            TZ: America/New_York
        volumes:
            - C:\Data\Docker\Nzbget\Config:/config
            - C:\Data\Media\Downloads:/downloads
        ports:
            - 6789:6789
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.10

    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            PUID: 0
            PGID: 0
            TZ: America/New_York
            UMASK_SET: 022
            WEBUI_PORT: 8080
        volumes:
            - C:\Data\Docker\Qbittorrent\Config:/config
            - C:\Data\Docker\Qbittorrent\Downloads:/downloads
            - C:\Data\Media\TV:/tv
            - C:\Data\Media\Movie:/movies
        ports:
            - 31321:31321
            - 31321:31321/udp
            - 8080:8080
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.11

    hydra:
        image: linuxserver/hydra2
        container_name: hydra
        environment:
            PUID: 0
            PGID: 0
            TZ: America/New_York
        volumes:
            - C:\Data\Docker\Hydra2:/config
            - C:\Data\Media\Downloads:/downloads
        ports:
            - 5076:5076
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.12
    
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        environment:
            PUID: 0
            PGID: 0
            TZ: America/New_York
        volumes:
            - C:\Data\Docker\Jackett\Config:/config
            - C:\Data\Media\Downloads:/downloads
        ports:
            - 9117:9117
        restart: always
        networks:
            static-network:
               ipv4_address: 172.20.0.13
               
networks:
    static-network:
        ipam:
            config:
              - subnet: 172.20.0.0/16